import { FC } from 'react';


import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Navbar } from '../Navbar';
import styles from '../layouts/Layout.module.css';


const inter = Inter({ subsets: ['latin'] });

interface Props{
    children?: React.ReactNode
}
export const MainLayout :FC<Props> = ( {children} ) => {
    return (
        <div>
            <Head>
                <title>App</title>
                <meta
                    name="description"

                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={`${styles.main} ${inter.className}`}>
                {children}
            </main>
        </div>
    );
};
